name: ci-test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.22
      id: go 
  
    - name: Check out code into Go module directory
      uses: actions/checkout@v2

# These are pulled in automatically
#    - name: Get dependencies
#      run: |
#        echo go get -v -t -d ./...
#         if [ -f Gopkg.toml ]; then
#          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#          dep ensure
#         fi
# And this is done during the test anyway.
#    - name: Build
#      run: go build -v 
#
    - name: Test
      run: make test